### ISSUE TITLE
Makefile error by building Simu5g

### ISSUE THREAD

**Issue by Parvaaaa** [Unipisa/Simu5G#65]
Hello all,

I am Building Simu5g on Windows10, OMNeT++6.0, and INET4.4.0.  I have the same issue as #6 and #54. 
I tried the first two options to install Simu5g:
1. Download and install Simu5G directly from the OMNeT++ IDE  and
2. Download the source code and build Simu5G manually 
I also tried to clone the code from the GitHub repository. But, I still have the makefile errors.
![Capture](https://user-images.githubusercontent.com/110019478/180953895-99aca939-7bfc-42ea-89ee-5c531e94f7f9.PNG)
I have tried both solutions suggested in #6, but they didn't work.

Thank you in advance for your help. 

Best regards, 
Parva

**Comment by MaFe1401** [comment]
Hi, I am facing the same issue. Have you found any solution?

**Comment by Parvaaaa** [comment]
> Hi, I am facing the same issue. Have you found any solution?

Not yet.

**Comment by giovanninardini** [comment]
Hello,

we are aware about problems about linking Simu5G and INET on Windows. We are working together with the INET team in order to try to find a solution. 

In the meantime, you could use Simu5G on a Linux machine or downloading the pre-arranged VM from [here](http://simu5g.org/simu5g-pnp.html)

**Comment by Parvaaaa** [comment]
> Hello,
> 
> we are aware about problems about linking Simu5G and INET on Windows. We are working together with the INET team in order to try to find a solution.
> 
> In the meantime, you could use Simu5G on a Linux machine or downloading the pre-arranged VM from [here](http://simu5g.org/simu5g-pnp.html)

Thank you for your response. Would you please let us know whenever it is fixed?

**Comment by giovanninardini** [comment]
Hello,

the issue can be solved by downloading the latest version of INET, v.4.4.1, and the master branch version of Simu5G.
We will make a new Simu5G minor release including this fix soon.

**Comment by Parvaaaa** [comment]
Thank you very much.

**Comment by monologconnor** [comment]
> 

Hi @Parvaaaa , is your building process running well now?

I just followed @giovanninardini 's instruction to download `INET 4.4.1` and the latest code from master branch, and also perform the process mentioned in https://github.com/Unipisa/Simu5G/issues/6, by adding line `LDFLAGS += -Wl,-Xlink=-force:multiple` at the buttom of `Custom` tab under `makemake`, but the error still presents:

```
D:\Documents\Omnetpp\omnetpp-6.0\tools\win32.x86_64\mingw64\bin/llvm-ar.exe: error: unable to load '../out/gcc-debug/src/libsimu5g_dbg.dll.a': No such file or directory
make[1]: *** [Makefile:409: ../out/gcc-debug/src/libsimu5g_dbg.dll] Error 1
make[1]: Leaving directory '/d/Documents/Simu5G/Simu5G-master-1.2.1/src'
make: *** [Makefile:2: all] Error 2
```

**Comment by Parvaaaa** [comment]
> > 
> 
> Hi @Parvaaaa , is your building process running well now?
> 
> I just followed @giovanninardini 's instruction to download `INET 4.4.1` and the latest code from master branch, and also perform the process mentioned in #6, by adding line `LDFLAGS += -Wl,-Xlink=-force:multiple` at the buttom of `Custom` tab under `makemake`, but the error still presents:
> 
> ```
> D:\Documents\Omnetpp\omnetpp-6.0\tools\win32.x86_64\mingw64\bin/llvm-ar.exe: error: unable to load '../out/gcc-debug/src/libsimu5g_dbg.dll.a': No such file or directory
> make[1]: *** [Makefile:409: ../out/gcc-debug/src/libsimu5g_dbg.dll] Error 1
> make[1]: Leaving directory '/d/Documents/Simu5G/Simu5G-master-1.2.1/src'
> make: *** [Makefile:2: all] Error 2
> ```

Hi, yes it is working for me now. Maybe you should first try changing the `Makemake` setting back to default. What I did is as follows: 
1) I installed INET 4.4.1 from the IDE (Help->Install simulation models...).
2) I cloned the master branch (Import->Git->Projects from Git(with smart import)->Clone URI).
and it runs perfectly.

**Comment by MaFe1401** [comment]
> > 
> 
> Hi @Parvaaaa , is your building process running well now?
> 
> I just followed @giovanninardini 's instruction to download `INET 4.4.1` and the latest code from master branch, and also perform the process mentioned in #6, by adding line `LDFLAGS += -Wl,-Xlink=-force:multiple` at the buttom of `Custom` tab under `makemake`, but the error still presents:
> 
> ```
> D:\Documents\Omnetpp\omnetpp-6.0\tools\win32.x86_64\mingw64\bin/llvm-ar.exe: error: unable to load '../out/gcc-debug/src/libsimu5g_dbg.dll.a': No such file or directory
> make[1]: *** [Makefile:409: ../out/gcc-debug/src/libsimu5g_dbg.dll] Error 1
> make[1]: Leaving directory '/d/Documents/Simu5G/Simu5G-master-1.2.1/src'
> make: *** [Makefile:2: all] Error 2
> ```

Same for me. Error still present even when following @Parvaaaa 's steps.

**Comment by monologconnor** [comment]
> > > 
> > 
> > 
> > Hi @Parvaaaa , is your building process running well now?
> > I just followed @giovanninardini 's instruction to download `INET 4.4.1` and the latest code from master branch, and also perform the process mentioned in #6, by adding line `LDFLAGS += -Wl,-Xlink=-force:multiple` at the buttom of `Custom` tab under `makemake`, but the error still presents:
> > ```
> > D:\Documents\Omnetpp\omnetpp-6.0\tools\win32.x86_64\mingw64\bin/llvm-ar.exe: error: unable to load '../out/gcc-debug/src/libsimu5g_dbg.dll.a': No such file or directory
> > make[1]: *** [Makefile:409: ../out/gcc-debug/src/libsimu5g_dbg.dll] Error 1
> > make[1]: Leaving directory '/d/Documents/Simu5G/Simu5G-master-1.2.1/src'
> > make: *** [Makefile:2: all] Error 2
> > ```
> 
> Same for me. Error still present even when following @Parvaaaa 's steps.

Hi @MaFe1401 , I just successfully built the project and not sure if my solution helps for you.

I do not know the specific reason for that but the compiling behaviour is different to different method of importing Simu5G. 

I have `INET 4.4.1` installed from `Help->Install simulation models...` before the procedures below. And just check the `VERSION` file under `inet4.4` folder to make sure the version number is `4.4.1`, since `Install simulation models...` were actually providing `4.4.0` a week ago.

Initially I downloaded the zipped source code from GitHub manually and using `Existing Projects into Workplace` option while importing, followed by selecting the unzipped source code. However that does not work, even with the latest source code, the error of library linking still occurs.
Then I tried the procedure done by @Parvaaaa , which is to import the project using `Import->Git->Projects from Git(with smart import)->Clone URI`, where the `URL` filed is filled with the `HTTP git address` of this project, which is `https://github.com/Unipisa/Simu5G.git`. And I successfully built the project without any modification on configurations. 

I'm not certain on how you importted the project but my experience does help to you.

**Comment by yuvan257** [comment]
hi all, 
i want to make work simu5g with windows 11.. 
the same error which u guys all got, is same for me.
my specs -
win 11 
omnetpp - 6.0.1
inet - 4.4.1 
simu5g - 1.2.1

**Comment by LucaDoncic77** [comment]
> > > > 
> > > 
> > > 
> > > Hi @Parvaaaa , is your building process running well now?
> > > I just followed @giovanninardini 's instruction to download `INET 4.4.1` and the latest code from master branch, and also perform the process mentioned in #6, by adding line `LDFLAGS += -Wl,-Xlink=-force:multiple` at the buttom of `Custom` tab under `makemake`, but the error still presents:
> > > ```
> > > D:\Documents\Omnetpp\omnetpp-6.0\tools\win32.x86_64\mingw64\bin/llvm-ar.exe: error: unable to load '../out/gcc-debug/src/libsimu5g_dbg.dll.a': No such file or directory
> > > make[1]: *** [Makefile:409: ../out/gcc-debug/src/libsimu5g_dbg.dll] Error 1
> > > make[1]: Leaving directory '/d/Documents/Simu5G/Simu5G-master-1.2.1/src'
> > > make: *** [Makefile:2: all] Error 2
> > > ```
> > 
> > 
> > Same for me. Error still present even when following @Parvaaaa 's steps.
> 
> Hi @MaFe1401 , I just successfully built the project and not sure if my solution helps for you.
> 
> I do not know the specific reason for that but the compiling behaviour is different to different method of importing Simu5G.
> 
> I have `INET 4.4.1` installed from `Help->Install simulation models...` before the procedures below. And just check the `VERSION` file under `inet4.4` folder to make sure the version number is `4.4.1`, since `Install simulation models...` were actually providing `4.4.0` a week ago.
> 
> Initially I downloaded the zipped source code from GitHub manually and using `Existing Projects into Workplace` option while importing, followed by selecting the unzipped source code. However that does not work, even with the latest source code, the error of library linking still occurs. Then I tried the procedure done by @Parvaaaa , which is to import the project using `Import->Git->Projects from Git(with smart import)->Clone URI`, where the `URL` filed is filled with the `HTTP git address` of this project, which is `https://github.com/Unipisa/Simu5G.git`. And I successfully built the project without any modification on configurations.
> 
> I'm not certain on how you importted the project but my experience does help to you.
still cannot work...

**Comment by L0rd0fCode** [comment]
Hi everyone. Is there any solution in case neither of previous doesn't help? Would be very grateful if somebody helped me to fix this issue ASAP

**Comment by mukesh123m** [comment]
Yea i get the same error while using inet4.5 and simu5g from git using above method. even disabled clang does not help.
Any pointers will help.  do i need to downgrade inet version?

clang++: error: linker command failed with exit code 1 (use -v to see invocation)
C:/Users/amita/Downloads/omnetpp-6.0.1-windows-x86_64/omnetpp-6.0.1/tools/win32.x86_64/mingw64/bin/llvm-ar.exe: error: unable to load '../out/clang-debug/src/libsimu5g_dbg.dll.a': No such file or directory
make[1]: *** [Makefile:424: ../out/clang-debug/src/libsimu5g_dbg.dll] Error 1
make[1]: Leaving directory '/c/Users/amita/Downloads/omnetpp-6.0.1-windows-x86_64/omnetpp-6.0.1/git/Simu5G/src'
make: *** [Makefile:2: all] Error 2
"make MODE=debug -j8 all" terminated with exit code 2. Build might be incomplete.

**Comment by mukesh123m** [comment]
Worked after moving to inet4.4 and rebuilding simu5g refering inet4.4.   Now going to test it to see how useful is simu5g
